# Generated by Django 5.0.4 on 2024-06-18 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_me", models.TextField(blank=True, null=True)),
                (
                    "video_intro",
                    models.FileField(blank=True, null=True, upload_to="video_intros/"),
                ),
                ("user_cv", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "profilephoto",
                    models.ImageField(
                        default="profilephoto/profile.png", upload_to="profilephoto/"
                    ),
                ),
                ("profession", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
    ]
