# Generated by Django 5.0.4 on 2024-06-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userportfoliyo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=250)),
                ("organization", models.CharField(max_length=250)),
                ("year", models.DateField()),
                ("description", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_workexperience",
                        to="userportfoliyo.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkExperience",
                "verbose_name_plural": "WorkExperience",
            },
        ),
    ]
