# Generated by Django 5.0.4 on 2024-06-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userportfoliyo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fb_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="x_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profession",
            field=models.CharField(max_length=250),
        ),
    ]
