# Generated by Django 5.0.4 on 2024-06-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userportfoliyo", "0002_profile_fb_link_profile_github_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Techonology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="techonology",
            field=models.ManyToManyField(to="userportfoliyo.techonology"),
        ),
    ]
