# Generated by Django 5.0.4 on 2024-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userportfoliyo", "0003_techonology_profile_techonology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techonology",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
