# Generated by Django 5.0.4 on 2024-06-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userportfoliyo", "0003_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userportfoliyo.profile"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="technology_used",
            field=models.ManyToManyField(to="userportfoliyo.techonology"),
        ),
    ]
