# Generated by Django 5.0.4 on 2024-06-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userportfoliyo", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="userportfoliyo.blog",
            ),
            preserve_default=False,
        ),
    ]
