from django.contrib import admin
from .models import *

admin.site.register(Profile)
admin.site.register(Techonology)
admin.site.register(Profession)
admin.site.register(WorkExperience)
admin.site.register(Project)
admin.site.register(Blog)
admin.site.register(Comment)
admin.site.register(Review)
admin.site.register(TechRole)
admin.site.register(Organization)
admin.site.register(ServiceReview)
admin.site.register(SoftSkills)
admin.site.register(StudyField)
admin.site.register(Education)
admin.site.register(Certification)
admin.site.register(Institution)
admin.site.register(UserProfileStatistic)